### ISSUE TITLE
Duplicate border styles

### ISSUE THREAD

**Issue by gauntface** [dracula/dracula-ui#148]
I think there are duplicate border styles:

https://github.com/dracula/dracula-ui/blob/92496c8d8784e1ba9b32c2bb664f1dbfd6e463f2/src/styles/backgrounds.css#L65-L68

https://github.com/dracula/dracula-ui/blob/main/src/styles/borders.css#L15-L17

**Comment by leandrocunha** [comment]
@gauntface not really, in my opinion. The class `.border-<color>{...}` has a property `border-color` + custom property (CSS variable) `--borderColor` where there are no conflicts between them. I only didn't understand why, because I'm not able to find where this variable is being used. What do you think?

**Comment by gauntface** [comment]
It just seems like they duplicate output (although perhaps postcss is doing something clever and merging duplicate classes).
 
I couldn't find a use of the --borderColor variable either. There is also a small difference between the colors where one has `grey`, the other doesn't.

Feel free to close if this all seems expected / good.
